### ISSUE TITLE
Is there a way to use this on blueprints?

### ISSUE THREAD

**Issue by detly** [imiric/flask-sass#1]
Is there a way to apply this to blueprints while avoiding circular dependencies? For example, in my skeleton project [flaskery](https://github.com/detly/flaskery), where would you put the `sass()` call to set things up?

As far as I can see, the use of `static_url_path` isn't compatible with blueprints that have their own static URL path, but I could be wrong.

**Comment by lolobosse** [comment]
+1

**Comment by imiric** [comment]
Hi there, and sorry about the delay with answering.

I'm sure you've noticed that this repo hasn't been updated in 5 years, since I'm not using Flask nor Sass anymore, and this extension was never tested with blueprints (or at all, actually, since it has no tests).

So for all intents and purposes consider this project abandoned, but you're free to fork it yourself to add blueprint support. I'll update the README to reflect this.

My apologies, and thanks for the interest.

Cheers,

Ivan
